### ISSUE TITLE
pre-release tickets

### ISSUE THREAD

**Issue by paultag** [sunlightlabs/indiana-docs#1]
Top-notch work. Looks great, totally works. Nice hack!

Some things we should tie up:

 - [x] flake8 this guy, it's small - I see a trailing space and unspaced operators 
 - [x] add a small landing page at `/`, explaining the very basics of what we are doing here; nothing fancy.
 - [x] move `from hidden_settings import in_api_key` into an environ varable
 - [x] add a magic one-click-heroku deploy button, ask for IN API key at deploy-time
 - [x] 429 response code forwarding

Nice work! :confetti_ball:

**Comment by paultag** [comment]
Any chance we could get this stood up today?

Also relevent: @timball can we have `in.proxy.openstates.org` pointed at this once it's up? Also aggresive Varnish. Documents shouldn't expire, so as far in the future as we can

**Comment by rshorey** [comment]
possibly - might need help with some of these items, but most should be fast.

**Comment by paultag** [comment]
No worries if not, but yeah, seems like these are all a few minutes of work :)

:+1:

**Comment by rshorey** [comment]
Everything except the deploy button is done, since I don't know exactly where we're deploying it to, but app.json is there.
 
Note that there is no styling or anything on the index page, are we OK with that or do you want me to make it look like something other than raw text?

Things that remain:
- [ ] @paultag OK's the text on the index page
- [ ] change the endpoint to whatever we want it to actually be called (it's currently got a todo in the name)
- [ ] put the deploy button wherever we want it (the github readme page?)

Anything I'm missing?

**Comment by paultag** [comment]
Raw text is cool for now; it's not user facing, I just didn't want to have users see a 500 if they hit the root domain -- can we match upstream's URL, just replacing in.gov with the 'proxy' name?

**Comment by paultag** [comment]
Other than that I think we're gold!

**Comment by rshorey** [comment]
per convo with @paultag we are ready to test

**Comment by paultag** [comment]
Outstanding; mind putting the URL in the README?

**Comment by paultag** [comment]
https://raw.githubusercontent.com/opencivicdata/opencivicdemo/master/README.md for an example

**Comment by rshorey** [comment]
yeah, got it, sorry, I somehow thought you needed the heroku destination for that but got it now!

**Comment by paultag** [comment]
Win!
